name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      FRONTEND_SERVER_URL: ${{ secrets.FRONTEND_SERVER_URL }}
      BACKEND_SERVER_URL: ${{ secrets.BACKEND_SERVER_URL }}
      BACKEND_SERVER_PORT: ${{ secrets.BACKEND_SERVER_PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      HASH_SECRET: ${{ secrets.HASH_SECRET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm run ci
    - name: Build (if present)
      run: npm run build --if-present
    - name: Install Playwright and required libs
      run: npx playwright install --with-deps
    - name: Run end-to-end tests
      run: npm run playwright
    - name: Run ESLint
      run: npm run eslint
    - name: Run unit tests
      run: npm run jest
